import { chromium } from 'playwright';
import { spawn } from 'node:child_process';
import { readFile,mkdir } from 'node:fs/promises';
import assert from 'node:assert/strict';
const secrets=[];
const server=spawn(process.execPath,['scripts/dev.mjs','--synthetic'],{stdio:['ignore','pipe','pipe']});
let browser, page, student;
try {
  await new Promise((resolve,reject)=>{const timeout=setTimeout(()=>reject(new Error('Local server startup timed out')),30000);server.stdout.on('data',d=>{if(String(d).includes('Local full-stack server')){clearTimeout(timeout);resolve();}});server.on('exit',()=>reject(new Error('Local server exited')));});
  const {adminCode}=JSON.parse(await readFile('test-results/ui-credentials.json','utf8'));secrets.push(adminCode);
  browser=await chromium.launch({headless:true});
  page=await browser.newPage({viewport:{width:1440,height:1000}}); const errors=[];
  page.on('pageerror',e=>errors.push(e.message));
  await page.goto('http://localhost:5173/?department=1');
  await page.getByLabel('Teacher or admin code').fill(adminCode);
  await page.getByRole('button',{name:'Open Teacher Portal',exact:true}).click();
  await page.getByRole('button',{name:'Department accounts',exact:true}).waitFor();
  await page.getByRole('button',{name:'EnScribe',exact:true}).click();
  await page.getByRole('button',{name:'New writing assignment'}).click();
  for(const [label,value] of Object.entries({Course:'Synthetic browser test',Section:'Period 1',Title:'Browser verification writing','Assignment prompt':'Analyze how the gate creates tension.','Teacher-provided rubric':'Explain the reasoning behind your interpretation.'}))await page.getByLabel(label,{exact:true}).fill(value);
  await page.getByLabel('Status',{exact:true}).selectOption('open');
  await page.getByRole('button',{name:'Save assignment',exact:true}).click();
  await page.getByText('Assignment saved. Open it before sharing the link.',{exact:true}).waitFor();
  await page.screenshot({path:'test-results/teacher-desktop.png',fullPage:true});
  const link=await page.locator('a[href^="/?writing="]').getAttribute('href');
  const access=page.locator('form').filter({has:page.getByRole('heading',{name:'Private student access'})});
  await access.getByLabel('First name',{exact:true}).fill('Fictional');
  await access.getByLabel('Last name',{exact:true}).fill('Writer');
  await access.getByLabel('Student email',{exact:true}).fill('browser@example.invalid');
  await access.getByRole('button',{name:'Issue private student code'}).click();
  await access.locator('.private-code code').waitFor();
  const studentCode=await access.locator('.private-code code').innerText();secrets.push(studentCode);
  student=await browser.newPage({viewport:{width:390,height:844}});student.on('pageerror',e=>errors.push(e.message));
  await student.goto('http://localhost:5173'+link);
  await student.getByLabel('Private student code',{exact:true}).fill(studentCode);
  await student.getByRole('button',{name:'Open workspace'}).click();
  await student.getByLabel('Independent original draft',{exact:true}).fill('The gate suggests a change. Ari waits beside the empty bench, which makes the action feel unresolved.');
  await student.getByRole('button',{name:'Preserve original and begin'}).click();
  await student.getByLabel('Working draft',{exact:true}).waitFor();
  assert.equal(await student.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth+1),false,'No horizontal overflow on mobile');
  await student.screenshot({path:'test-results/student-mobile.png',fullPage:true});
  await student.getByLabel('Working draft',{exact:true}).fill('The closed gate contrasts with Ari’s continued waiting. I need to explain how those actions relate.');
  await student.getByLabel('Explain what you changed or why you rejected a suggestion').fill('I identified the contrast more precisely.');
  await student.getByRole('button',{name:'Save revision',exact:true}).click();
  await student.getByText('Saved. This is not a submission.',{exact:true}).waitFor();
  await student.getByLabel('Explain what you changed or why you rejected a suggestion').fill('I kept this revision because it states the next reasoning step.');
  await student.getByLabel('Final reflection: What changed in your thinking, and which choices remain yours?').fill('I chose which contrast mattered and why it needs explaining.');
  await student.getByRole('button',{name:'Submit to teacher',exact:true}).click();
  await student.getByText('Submitted successfully. Your teacher can now review this version.',{exact:true}).waitFor();
  assert.equal(await student.getByLabel('Working draft',{exact:true}).isDisabled(),true);
  await page.getByRole('button',{name:'Refresh records'}).click();
  await page.getByText('Fictional Writer · submitted',{exact:true}).click();
  await page.getByRole('button',{name:'Reopen for revision'}).click();
  await page.getByText('Fictional Writer · draft',{exact:true}).waitFor();
  student.once('dialog',d=>d.accept());
  await Promise.all([student.waitForResponse(r=>r.url().includes('/api/department') && r.request().postDataJSON().action==='student-read'),student.getByRole('button',{name:'Reload saved version'}).click()]);
  await student.getByRole('button',{name:'Save revision',exact:true}).waitFor();
  assert.equal(await student.getByLabel('Working draft',{exact:true}).isDisabled(),false);
  await page.getByRole('button',{name:'Try both tools',exact:true}).click();
  await page.getByRole('button',{name:'Try EnDepth',exact:true}).click();
  await page.getByRole('link',{name:'Open fictional sample workspace ↗'}).waitFor();
  const depthLink=await page.getByRole('link',{name:'Open fictional sample workspace ↗'}).getAttribute('href');
  const depth=await browser.newPage({viewport:{width:1440,height:1000}});depth.on('pageerror',e=>errors.push(e.message));
  await depth.goto('http://localhost:5173'+depthLink);
  await depth.getByText('Example: the empty bench',{exact:true}).first().waitFor();
  await depth.screenshot({path:'test-results/endepth-desktop.png',fullPage:true});
  assert.deepEqual(errors,[]);
  console.log('PASS: desktop teacher creation/import access; mobile original/revision/submit/reopen; EnDepth sample link; no React errors; no mobile overflow. Live AI was not called.');
} catch(e) {
  if(page) await page.screenshot({path:'test-results/failure-redacted.png',fullPage:true,mask:[page.locator('code'),page.locator('input[type=password]')]}).catch(()=>{});
  if(student) await student.screenshot({path:'test-results/student-failure-redacted.png',fullPage:true,mask:[student.locator('code'),student.locator('input[type=password]')]}).catch(()=>{});
  let message=String(e.stack || e) + (student ? '\nStudent visible state: '+await student.locator('body').innerText().catch(()=> '') : '');for(const secret of secrets)message=message.replaceAll(secret,'[redacted synthetic credential]');console.error(message);process.exitCode=1;
} finally {await browser?.close();server.kill('SIGTERM');}
